apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "adu-watcher.fullname" . }}
  labels:
    {{- include "adu-watcher.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "adu-watcher.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "adu-watcher.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "adu-watcher.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.deployment.containerPort }}
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: {{ .Values.deployment.httpPort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: adu-pd
              mountPath: {{ .Values.deployment.mountPath }}
            - name: adu-timezone
              mountPath: /etc/localtime
            - name: pg-secret
              mountPath: /secret
      volumes:
        - name: adu-pd
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.persistentVolumeClaim.name }}
        - name: adu-timezone
          hostPath:
            path: {{ .Values.timezone.path }}
        - name: pg-secret
          secret:
            secretName: document-database-pg-secret
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- if eq .Values.affinity.podAntiAffinity "hard" }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - {{ include "adu-watcher.fullname" . }}
              topologyKey: "kubernetes.io/hostname"
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
  {{- with .Values.updateStrategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
